### ISSUE TITLE
Savegame decryptor link dead

### ISSUE THREAD

**Issue by sollevix67** [RayRay5/ets2_savegame_editor#7]
The link to Savegame decryptor is dead.

**Comment by Bluscream** [comment]
https://forum.scssoft.com/viewtopic.php?t=245874

https://github.com/ncs-sniper/SII_Decrypt

**Comment by Tampa** [comment]
Those links are also dead

**Comment by RayRay5** [comment]
Bluescream provided the correct alternative link. BUT
I just saw that those links are also dead. Can't find a serious, stable and working solution at the moment.
I will edit the read me file right now

**Comment by RayRay5** [comment]
Link seems to be down since a few weeks. Unfortunately, Tampa, you were the first one to report it.

If anyone reading this finds an alternative solution, please comment here, so I can have a look

**Comment by Tampa** [comment]
I do still have the decode and decrypt as executables floating around, though the decode does not function properly running out of memory for some reason. I could upload them somewhere though, just let me know.

Question I have though: How do you, now, decrypt and decode the game.sii to change things, I tried the various decrypters and editors and none seem to work anymore?

**Comment by RayRay5** [comment]
Apperently there is no other way, other than having the old executables somewhere on disk.

Regarding reuploading: Those decrypters are not my work and you should check the terms of their respective creators.
GENERALLY SPEAKING: BE CAREFUL WITH REUPLOADING OTHER PEOPLE'S WORK. IT MIGHT BE AGAINST TaC (terms and conditions) OR LICENSE TO REUPLOAD THEM. DOUBLE CHECK THAT! I DO NOT SUPPORT THE BREAKING OF ANY LICENSE OR TaC!

**Comment by RayRay5** [comment]
Just found something that might work. (One of the people who forked my SaveEditor also forked an Sii Decrypter)
It looks like a fork from a fork of Snipers SII Decrypter. The version is a little bit older, but should still work. Haven't checked it yet, but it should work

https://github.com/codemastersolucoes/SII_Decrypt

**Comment by Tampa** [comment]
How would I go about checking terms of something that has essentially been purged from most places, let alone the fact it seems to be the most disregarded thing in the entire community to reupload mods to the various pages anyways. I don't even remember where exactly they came from to begin with either, I'll see what I can find.

The main issue is the decoder, decrypting is still possible as far as I know that should still float around somewhere, but the decoding into readable data rather than hex or whatever, that's the part that runs out of memory and that seems impossible to find and all current versions of the save editor seem to not work with the decrypter I have.

Why is it that this has been abandoned or no longer works or whatever? I thought this was something useful many people liked, the thread on the forums is a couple pages long even and the work has gone into various other programs, kinda strange that is has been kinda purged or completely forgotten about.

**Comment by RayRay5** [comment]
I have just merged the updated link from V3ntus. Please try that link
